services:
  postgresdb:
    image: postgres
    container_name: postgres-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tdsynnex123
      POSTGRES_DB: Wildfire_Response_Database
    ports:
      - 5432:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8011:8080
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ui
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: administrator@gmail.com
      PGADMIN_DEFAULT_PASSWORD: tdsynnex123
    depends_on:
      - postgresdb